Branch person of contact
AY2223S1-CS2103T-T09-1/tp pull request #111
Opened 2022-10-04 10:17 UTC by quannam0124

2022-10-04 16:43 UTC, notle1706 requested changes
Many Javadocs should be corrected as they are still using company instead of POC. Perhaps we could also discuss if we need the UniquePocList class. Other than that, well-done everything else looks great!

2022-10-04 16:43 UTC, notle1706 commented on src/main/java/seedu/address/model/poc/Phone.java
> +public class Phone {
Why is the class name for this class `Phone` and not `PersonPhone` while the class name for `Name` is `PersonName`? Should they be standardised?

2022-10-04 16:43 UTC, notle1706 commented on src/main/java/seedu/address/model/poc/UniquePocList.java
> + * A list of companies that enforces uniqueness between its elements and does not allow nulls.
"companies" should be changed to POCs instead. This is a recurring issue throughout the file.

2022-10-04 16:43 UTC, notle1706 commented on src/main/java/seedu/address/model/poc/UniquePocList.java
> +public class UniquePocList implements Iterable<Poc> {
Do we really need this class for POC? POC only belongs to a company and as of now, there shouldn't be more than one POC per company as well.

2022-10-04 16:43 UTC, notle1706 commented on src/main/java/seedu/address/model/poc/exceptions/DuplicatePocException.java
> +        super("Operation would result in duplicate companies");
Should this be "Operation would result in duplicate POCs"?

2022-10-04 16:43 UTC, notle1706 commented on src/main/java/seedu/address/model/poc/exceptions/DuplicatePocException.java
> + * Signals that the operation will result in duplicate Companies
Companies here should be POCs as well.

2022-10-04 16:43 UTC, notle1706 commented on src/main/java/seedu/address/model/poc/exceptions/PocNotFoundException.java
> + * Signals that the operation is unable to find the specified company.
company should be POC.

2022-10-04 17:42 UTC, jicsontoh requested changes
Overall, great work! Some changes to be made for the description of the Poc class as well as the other comments. Good effort! :)

2022-10-04 17:42 UTC, jicsontoh commented on src/main/java/seedu/address/model/poc/UniquePocList.java
> +     * Replaces the company {@code target} in the list with {@code editedCompany}.
Should be poc instead of company

2022-10-04 17:42 UTC, jicsontoh commented on src/main/java/seedu/address/model/poc/UniquePocList.java
> +     * Removes the equivalent company from the list.
This is also a similar issue

2022-10-04 17:42 UTC, jicsontoh commented on src/main/java/seedu/address/model/poc/UniquePocList.java
> +    public void setPocs(List<Poc> pocs) {
Perhaps could consider renaming this method to replacePocs to prevent potential confusion from the previous method setPoc

2022-10-04 17:42 UTC, jicsontoh commented on src/test/java/seedu/address/model/poc/UniquePocListTest.java
> +        Poc editedAlice = new PocBuilder(ALICE).withTags(VALID_TAG_HUSBAND)
This tag may not be appropriate in the context of a POC of a company

2022-10-06 02:13 UTC, ElginL requested changes
A few trivial changes might improve it, and some possible missing test cases. Otherwise, LGTM, good work 👍

2022-10-06 02:13 UTC, ElginL commented on src/main/java/seedu/address/model/poc/PersonName.java
> + * Represents a Poc's name in the address book.
Might be better if Poc is written as point-of-contact to make it more descriptive here

2022-10-06 02:13 UTC, ElginL commented on src/main/java/seedu/address/model/poc/Phone.java
> +
Trivial issue, but I think it will look nicer if there's only 1 empty line here

2022-10-06 02:13 UTC, ElginL commented on src/main/java/seedu/address/model/poc/Poc.java
> + * Represents a person of contact in the company.
I think we should standardize it to point-of-contact

2022-10-06 02:13 UTC, ElginL commented on src/main/java/seedu/address/model/poc/Poc.java
> +    public boolean isSamePoc(Poc otherPerson) {
Would `otherPoc` be better than `otherPerson` right here for the parameter?

2022-10-06 02:13 UTC, ElginL commented on src/main/java/seedu/address/model/poc/UniquePocList.java
> +public class UniquePocList implements Iterable<Poc> {
I think we should still leave this class for now though, since there's a high chance we will have more POC in the future, but good note, maybe we can remove it next time

2022-10-06 02:13 UTC, ElginL commented on src/test/java/seedu/address/model/poc/EmailTest.java
> +public class EmailTest {
Tests looks good for EmailTest class. But have you considered toString() method test for Email class? (Since codecov is saying that it is not covered)

Probably something simple like this might do:
```java
@Test
public void toString_email_returnsValueInEmail() {
  String value = "test@test.com"; 
  Email email = new Email(value);
  assertEquals(email.toString(), value);
}
```

2022-10-06 02:13 UTC, ElginL commented on src/test/java/seedu/address/model/poc/NameTest.java
> +public class NameTest {
Might be better if we have a toString() method test as previously recommended in EmailTest

2022-10-06 02:13 UTC, ElginL commented on src/test/java/seedu/address/model/poc/PhoneTest.java
> +public class PhoneTest {
Might be better if there's a toString() test like in EmailTest

2022-10-06 02:13 UTC, ElginL commented on src/test/java/seedu/address/model/poc/PocTest.java
> +public class PocTest {
It might be better to have a toStringTest as recommended in EmailTest

2022-10-06 02:13 UTC, ElginL commented on src/test/java/seedu/address/testutil/PocBuilder.java
> +    public static final String DEFAULT_ADDRESS = "123, Jurong West Ave 6, #08-111";
I think address is no longer needed in PocBuilder considering a POC does not have an address

2022-10-06 04:50 UTC, notle1706 requested changes
A few changes to be made but otherwise it looks good!

2022-10-06 04:50 UTC, notle1706 commented on src/main/java/seedu/address/model/poc/UniquePocList.java
> + * As such, adding and updating of companies uses Poc#isSamePoc(Poc) for equality to ensure that the
"companies" should be changed to POCs instead. This is a recurring issue throughout the file.

2022-10-06 04:50 UTC, notle1706 commented on src/main/java/seedu/address/model/poc/UniquePocList.java
> +public class UniquePocList implements Iterable<Poc> {
Yes, I think your point is valid. Let's keep this class for now!

2022-10-06 04:50 UTC, notle1706 commented on src/main/java/seedu/address/model/poc/exceptions/DuplicatePocException.java
> + * (Companies are considered duplicates if they have the same identity).
"companies" should be changed to POCs instead.

2022-10-06 04:50 UTC, notle1706 commented on src/test/java/seedu/address/model/poc/UniquePocListTest.java
> +        Poc editedAlice = new PocBuilder(ALICE).withTags(VALID_TAG_HUSBAND)
Perhaps we can all work on this together in the next iteration as there are a lot of tags to change.

2022-10-06 04:50 UTC, notle1706 commented on src/test/java/seedu/address/testutil/TypicalPoc.java
> +    }*/
Why is this commented out?

2022-10-06 04:50 UTC, notle1706 commented on src/test/java/seedu/address/testutil/TypicalPoc.java
> +    public static List<Poc> getTypicalCompanies() {
Why is the name for this `getTypicalCompanies()`?

2022-10-06 04:54 UTC, quannam0124 commented on src/test/java/seedu/address/testutil/TypicalPoc.java
> +    }*/
This method requires Pocs to be integrated with companies so that the new companies can be added to the address book

2022-10-06 04:55 UTC, quannam0124 commented on src/test/java/seedu/address/testutil/TypicalPoc.java
> +    public static List<Poc> getTypicalCompanies() {
Thank you for pointing this out

2022-10-06 06:10 UTC, quannam0124 commented on src/test/java/seedu/address/model/poc/PocTest.java
> +public class PocTest {
A toString test has been added

2022-10-06 06:12 UTC, quannam0124 commented on src/main/java/seedu/address/model/poc/Poc.java
> +    public boolean isSamePoc(Poc otherPerson) {
otherPoc has been used instead. Thank you!

2022-10-06 06:12 UTC, notle1706 commented on src/main/java/seedu/address/model/poc/UniquePocList.java
> +    public void setPocs(List<Poc> pocs) {
Method name has changed to be an overloaded method.

2022-10-06 06:16 UTC, notle1706 approved these changes

2022-10-06 07:03 UTC, jicsontoh approved these changes
LGTM

2022-10-06 07:03 UTC, ElginL approved these changes
Nice changes! LGTM! Good job Quan 🥇 💯

2022-10-06 07:03 UTC, merged