Branch company poc and create command integration
AY2223S1-CS2103T-T09-1/tp pull request #123
Opened 2022-10-07 09:34 UTC by jicsontoh

2022-10-08 09:40 UTC, notle1706 requested changes
Looks good, just a few small changes to be made.

2022-10-08 09:40 UTC, notle1706 commented on src/main/java/seedu/address/logic/commands/CreateCommand.java
> + */
Perhaps the javadocs should be updated?

2022-10-08 09:40 UTC, notle1706 commented on src/main/java/seedu/address/logic/commands/CreateCommand.java
> +            + PREFIX_TAG + "friends "
Perhaps this tag can be changed to be more in context? eg. Main Poc

2022-10-08 15:34 UTC, ElginL approved these changes
Nice additions with clean code. LGTM

2022-10-08 15:34 UTC, ElginL commented on src/main/java/seedu/address/logic/commands/CreateCommand.java
> +public class CreateCommand extends Command {
A well written class that doesn't violate any of the code quality standards 👍

2022-10-08 15:36 UTC, jicsontoh commented on src/main/java/seedu/address/logic/commands/CreateCommand.java
> +public class CreateCommand extends Command {
Thank you Elgin

2022-10-09 04:36 UTC, notle1706 approved these changes

2022-10-09 04:36 UTC, merged