Add Filter Transaction Command
AY2223S1-CS2103T-T09-1/tp pull request #189
Opened 2022-10-19 16:02 UTC by jicsontoh

Implemented the Filter Transaction Command which filters all the transaction by buy or sell.

Updated the UI to reflect all the transactions based on the filter

Updated the Filter Command section in the UG

2022-10-20 08:08 UTC, notle1706 commented on src/main/java/seedu/address/logic/parser/FilterTransCmdParser.java
> + * Parses input arguments and creates a new FilterTransCommand object
I think you might be missing a fullstop here.

2022-10-20 08:09 UTC, notle1706 reviewed
You might want to check the javadocs

2022-10-20 10:06 UTC, jicsontoh commented
CodeCov failed to cover due to changes in UI

2022-10-20 10:11 UTC, jicsontoh commented on src/main/java/seedu/address/logic/parser/FilterTransCmdParser.java
> + * Parses input arguments and creates a new FilterTransCommand object
Sure, thank you.

2022-10-21 02:15 UTC, ElginL approved these changes
LGTM! Good work

2022-10-21 02:38 UTC, notle1706 requested changes
Good coding, however there are some documentations that should be change.

2022-10-21 02:38 UTC, notle1706 commented on src/main/java/seedu/address/logic/commands/FilterTransCommand.java
> + * Filters the all the transaction by all the clients.
Perhaps this sentence should be 'Filters all the transaction by all the clients.` instead?

2022-10-21 02:38 UTC, notle1706 commented on src/main/java/seedu/address/logic/parser/FilterTransCmdParser.java
> +     * @param userInput
Should there be a fullstop after this sentence?

2022-10-21 02:55 UTC, notle1706 requested changes
Code looks good but there are still some errors with the javdocs.

2022-10-21 02:55 UTC, notle1706 commented on src/main/java/seedu/address/logic/commands/FilterTransCommand.java
> +     * @return feedback message of the operation result for display
Perhaps this sentence should end with a fullstop.

2022-10-21 02:59 UTC, notle1706 approved these changes
LGTM good job!

2022-10-21 03:02 UTC, merged