Update target user profile, value proposition and user stories
AY2223S1-CS2103T-T09-1/tp pull request #81
Opened 2022-09-27 07:48 UTC by Jo3LW

2022-09-27 12:00 UTC, ElginL requested changes
I think there's a few possible changes that can be made to improve it. Good job 👍

2022-09-27 12:00 UTC, ElginL commented on docs/DeveloperGuide.md
> +* is not used to using CLI apps
I think this should be `is reasonably comfortable using CLI apps` and not `is not used to using CLI apps`? 

Since our application is mainly CLI over GUI 🤔

2022-09-27 12:00 UTC, ElginL commented on docs/DeveloperGuide.md
> -* can type fast
I think this two points are still relevant and can be kept, not sure what's your take on this

2022-09-27 12:00 UTC, ElginL commented on docs/DeveloperGuide.md
> +**Value proposition**: manage contacts faster than a typical mouse/GUI driven app and provides a clean and easy to use UI
Our google doc has more value propositions, I think it might be good to add them here

2022-09-27 12:00 UTC, ElginL commented on docs/DeveloperGuide.md
> +| `* * *` | business owner            | choose which comoant and point-of-contact to delete | save only relevant companys and point-of-contact to remove clutter |
There might be a typo here, `comoant` should be `company`

2022-09-27 12:00 UTC, ElginL commented on docs/DeveloperGuide.md
> +| `* * *` | forgetful businesss owner | see usage instructions                     | refer to instructions when I forget how to use the App             |
There might be a typo here `businesss` should be `business`

2022-09-27 12:00 UTC, ElginL commented on docs/DeveloperGuide.md
> +| `* * `  | efficient business owner  | sort the search result by price            | quickly know which company I have made the most transactio with    |
There might be a typo here, `transactio` should be `transaction`

2022-09-27 12:00 UTC, ElginL commented on docs/DeveloperGuide.md
> +| `* * *` | busy business owner       | quickly retrieve the date of the company   | save time without having to go through multiple layers             |
There might be a typo here `date` should be `data`

2022-09-28 08:03 UTC, notle1706 approved these changes
LGTM

2022-09-28 08:16 UTC, ElginL approved these changes
Nice 👍, LGTM

2022-09-28 08:17 UTC, merged